U/jrbogart/write fluxes speedup
LSSTDESC/skyCatalogs pull request #28
Opened 2022-08-27 00:06 UTC by JoanneBogart

This branch is based on u/jrbogart/write_fluxes. Additional features, in order of decreasing importance and complexity, are
1. Support for parallel processing when calculating galaxy fluxes in catalog_creator.py. That part of `_create_galaxy_flux_pixel(..)` which does the calculation is broken out into static routine `_do_galaxy_flux_chunk`.
2. Add command-line arguments `--flux-only`, `--main-only`, and `--overwrite-data` to `create_sc.py`   to give caller finer control over what will get done.  Add command-line argument `--flux-parallel` to specify # of subprocesses to create in 1.
3. Add entries to config to document magnitude cuts

2022-09-03 20:11 UTC, jchiang87 requested changes
I have handful of comments/suggestions.  The substantive ones arose from trying to run  `create_sc.py --flux-only` with existing skyCatalogs files.

2022-09-04 00:44 UTC, JoanneBogart commented on python/desc/skycatalogs/catalog_creator.py
> +            self._cat = open_catalog(config_file)
I expect so.  I only exercised this code with the environment variable SKYCATALOG_ROOT set which is probably why it worked for me.

2022-09-04 00:51 UTC, JoanneBogart commented on python/desc/skycatalogs/catalog_creator.py
> +        self._ps_flux_schema = make_star_flux_schema(self._logname)
Thanks for the comments.  I'll make at least most, possibly all, of the suggested changes  (there are a couple I have to look at more carefully). I also plan to add a call to initialize of bp path earlier, before creating the subprocesses, so the message doesn't show up multiple times.

2022-09-05 23:16 UTC, JoanneBogart commented on python/desc/skycatalogs/skyCatalogs.py
> +        if self._config['area_partition']['partition_type'] == 'healpix':
There is no real need for it and I didn't make it consistently. I will change it back.

2022-09-08 16:30 UTC, JoanneBogart commented
This is ready for another look, @jchiang87

2022-09-08 17:34 UTC, jchiang87 approved these changes
LGTM

2022-09-08 20:18 UTC, merged